/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthIdComponent: typeof import('./src/components/auth/AuthIdComponent.vue')['default']
    BCarousel: typeof import('bootstrap-vue-next/components/BCarousel')['BCarousel']
    BCarouselSlide: typeof import('bootstrap-vue-next/components/BCarousel')['BCarouselSlide']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    CaptchaWidget: typeof import('./src/components/auth/CaptchaWidget.vue')['default']
    ConnectionTypeSelector: typeof import('./src/components/ConnectionTypeSelector.vue')['default']
    DatingFilter: typeof import('./src/components/profiles/DatingFilter.vue')['default']
    DatingProfileForm: typeof import('./src/components/profiles/DatingProfileForm.vue')['default']
    ErrorComponent: typeof import('./src/components/ErrorComponent.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ImageEditor: typeof import('./src/components/profiles/ImageEditor.vue')['default']
    ImageUpload: typeof import('./src/components/profiles/ImageUpload.vue')['default']
    LoadingComponent: typeof import('./src/components/LoadingComponent.vue')['default']
    LoginIntent: typeof import('./src/components/auth/LoginIntent.vue')['default']
    LogoutButton: typeof import('./src/components/LogoutButton.vue')['default']
    ModalDialogComponent: typeof import('./src/components/ModalDialogComponent.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    OTPLogin: typeof import('./src/components/auth/OTPLogin.vue')['default']
    OtpLoginComponent: typeof import('./src/components/auth/OtpLoginComponent.vue')['default']
    ProfileCardComponent: typeof import('./src/components/profiles/ProfileCardComponent.vue')['default']
    ProfileForm: typeof import('./src/components/profiles/ProfileForm.vue')['default']
    ProfileImageComponent: typeof import('./src/components/profiles/ProfileImageComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubmitButtonComponent: typeof import('./src/components/SubmitButtonComponent.vue')['default']
    TagSelectComponent: typeof import('./src/components/profiles/TagSelectComponent.vue')['default']
    ToggleSwitch: typeof import('./src/components/ToggleSwitch.vue')['default']
  }
}
