/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCarousel: typeof import('bootstrap-vue-next/components/BCarousel')['BCarousel']
    BCarouselSlide: typeof import('bootstrap-vue-next/components/BCarousel')['BCarouselSlide']
    BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
    BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarToggle']
    BNavForm: typeof import('bootstrap-vue-next/components/BNav')['BNavForm']
    BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
    BNavItemDropdown: typeof import('bootstrap-vue-next/components/BNav')['BNavItemDropdown']
    ConnectionTypeSelector: typeof import('./src/components/ConnectionTypeSelector.vue')['default']
    DatingProfileForm: typeof import('./src/components/profiles/DatingProfileForm.vue')['default']
    ErrorComponent: typeof import('./src/components/ErrorComponent.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ImageEditor: typeof import('./src/components/profiles/ImageEditor.vue')['default']
    ImageUpload: typeof import('./src/components/profiles/ImageUpload.vue')['default']
    LightSwitch: typeof import('./src/components/LightSwitch.vue')['default']
    LoadingComponent: typeof import('./src/components/LoadingComponent.vue')['default']
    LogoutButton: typeof import('./src/components/LogoutButton.vue')['default']
    ModalDialogComponent: typeof import('./src/components/ModalDialogComponent.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    ProfileForm: typeof import('./src/components/profiles/ProfileForm.vue')['default']
    ProfileImageComponent: typeof import('./src/components/profiles/ProfileImageComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubmitButtonComponent: typeof import('./src/components/SubmitButtonComponent.vue')['default']
    TagSelectComponent: typeof import('./src/components/profiles/TagSelectComponent.vue')['default']
    ToggleSwitch: typeof import('./src/components/ToggleSwitch.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBColorMode: typeof import('bootstrap-vue-next/directives/BColorMode')['vBColorMode']
  }
}
