/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BBadge: typeof import('bootstrap-vue-next/components/BBadge')['BBadge']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCarouselSlide: typeof import('bootstrap-vue-next/components/BCarousel')['BCarouselSlide']
    BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckbox']
    BFormFile: typeof import('bootstrap-vue-next/components/BFormFile')['BFormFile']
    BFormFloatingLabel: typeof import('bootstrap-vue-next/components/BForm')['BFormFloatingLabel']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormInvalidFeedback: typeof import('bootstrap-vue-next/components/BForm')['BFormInvalidFeedback']
    BFormRadio: typeof import('bootstrap-vue-next/components/BFormRadio')['BFormRadio']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BFormSelectOption: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelectOption']
    BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
    BInput: typeof import('bootstrap-vue-next/components/BFormInput')['BInput']
    BListGroup: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroupItem']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
    BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
    BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
    BNavItemDropdown: typeof import('bootstrap-vue-next/components/BNav')['BNavItemDropdown']
    BOverlay: typeof import('bootstrap-vue-next/components/BOverlay')['BOverlay']
    BPlaceholderCard: typeof import('bootstrap-vue-next/components/BPlaceholder')['BPlaceholderCard']
    BPlaceholderWrapper: typeof import('bootstrap-vue-next/components/BPlaceholder')['BPlaceholderWrapper']
    BPopover: typeof import('bootstrap-vue-next/components/BPopover')['BPopover']
    BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
    BTooltip: typeof import('bootstrap-vue-next/components/BTooltip')['BTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
