import { z } from 'zod';
import { DatingProfileSchema, ProfileImageSchema, ProfileSchema } from './generated';

// XXX this dooesn't work with the present multipart setup
// without the `attachFieldsToBody: true` option, 
// the file is not attached to the body. Leaving this here for now but it's unused
export const uploadImageSchema = z.object({
  file: z.instanceof(File).refine(
    (file) => {
      // Check file size (max 5MB)
      const maxSize = 5 * 1024 * 1024; // 5MB
      return file.size <= maxSize;
    },
    { message: 'File size must be less than 5MB' }
  ).refine(
    (file) => {
      // Check file type
      const validTypes = ['image/jpeg', 'image/png', 'image/webp'];
      return validTypes.includes(file.type);
    },
    { message: 'File must be JPEG, PNG, or WebP' }
  ),
});

// export type UploadImage = z.infer<typeof UploadImageSchema>;



const publicProfileImageFields = {
  url: true,  // this isn't actually stored in the DB but is generated by the API
  mimeType: true,
  altText: true,
} as const;

export const publicProfileImageSchema = ProfileImageSchema
  .pick(publicProfileImageFields)


export type PublicProfileImageSchema = z.infer<typeof publicProfileImageSchema>;

export const ownerProfileImageSchema = ProfileImageSchema
  .pick({
    ...publicProfileImageFields,
    id: true,
  }).extend({
    primaryForProfile: ProfileSchema.optional(),
    primaryForDatingProfile: DatingProfileSchema.optional(),
    otherForDatingProfiles: z.array(DatingProfileSchema).optional(),
    otherForProfiles: z.array(ProfileSchema).optional(),
  });

export type OwnerProfileImageSchema = z.infer<typeof ownerProfileImageSchema>;

const createProfileImageSchema = ProfileImageSchema.pick({
  userId: true,
  mimeType: true,
  altText: true,
  storagePath: true,
  isModerated: true,
  contentHash: true,
});
export type CreateProfileImageSchema = z.infer<typeof createProfileImageSchema>;