/// <reference lib="WebWorker" />
import { precacheAndRoute } from 'workbox-precaching'
declare let self: ServiceWorkerGlobalScope

// Precache assets generated by Vite PWA plugin
precacheAndRoute(self.__WB_MANIFEST)

// Handle incoming push messages
self.addEventListener('push', (event) => {
  console.log('sw Push event received:', event) 
  if (!event.data) return

  const data = event.data.json()

  console.info('sw Push event received:', data)
  const title = data.title || 'Notification'
  const options: NotificationOptions = {
    body: data.body || '',
    icon: data.icon || '/favicon.ico',
    data: {
      url: data.url || '/',
    },
  }

  event.waitUntil(
    self.registration.showNotification(title, options)
  )
})

// Handle notification click
self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  const targetUrl = event.notification.data?.url || '/'
  event.waitUntil(
    self.clients.matchAll({ type: 'window' }).then((clientsArr) => {
      const client = clientsArr.find((c) => c.focused) || clientsArr[0]
      if (client) {
        return client.navigate(targetUrl).then(() => client.focus())
      } else {
        return self.clients.openWindow(targetUrl)
      }
    })
  )
})
